package io.chr1s.blog.domain;

import java.util.Date;

public class ArticlePost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_post.id
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_post.article_id
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_post.title
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_post.category
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    private Byte category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_post.show_public
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    private Boolean showPublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_post.del_flag
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    private boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_post.create_time
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_post.update_time
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_post.content
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_post.id
     *
     * @return the value of article_post.id
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_post.id
     *
     * @param id the value for article_post.id
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_post.article_id
     *
     * @return the value of article_post.article_id
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_post.article_id
     *
     * @param articleId the value for article_post.article_id
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_post.title
     *
     * @return the value of article_post.title
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_post.title
     *
     * @param title the value for article_post.title
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_post.category
     *
     * @return the value of article_post.category
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public Byte getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_post.category
     *
     * @param category the value for article_post.category
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public void setCategory(Byte category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_post.show_public
     *
     * @return the value of article_post.show_public
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public Boolean getShowPublic() {
        return showPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_post.show_public
     *
     * @param showPublic the value for article_post.show_public
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public void setShowPublic(Boolean showPublic) {
        this.showPublic = showPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_post.del_flag
     *
     * @return the value of article_post.del_flag
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public boolean isDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_post.del_flag
     *
     * @param delFlag the value for article_post.del_flag
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public void setDelFlag(boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_post.create_time
     *
     * @return the value of article_post.create_time
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_post.create_time
     *
     * @param createTime the value for article_post.create_time
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_post.update_time
     *
     * @return the value of article_post.update_time
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_post.update_time
     *
     * @param updateTime the value for article_post.update_time
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_post.content
     *
     * @return the value of article_post.content
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_post.content
     *
     * @param content the value for article_post.content
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}