package io.chr1s.blog.dao;

import io.chr1s.blog.domain.ArticlePost;
import io.chr1s.blog.domain.ArticlePostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ArticlePostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_post
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    int deleteByExample(ArticlePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_post
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    int insert(ArticlePost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_post
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    int insertSelective(ArticlePost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_post
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    List<ArticlePost> selectByExampleWithBLOBs(ArticlePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_post
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    List<ArticlePost> selectByExample(ArticlePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_post
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") ArticlePost record, @Param("example") ArticlePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_post
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ArticlePost record, @Param("example") ArticlePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_post
     *
     * @mbg.generated Sat Jul 13 23:41:50 CST 2019
     */
    int updateByExample(@Param("record") ArticlePost record, @Param("example") ArticlePostExample example);

    @Select("SELECT * FROM article_post LIMIT 0, 20")
    List<ArticlePost> pagination(@Param("pageNo") int pageNo, @Param("pageSize") int pageSize);

    @Select("SELECT * FROM article_post WHERE article_id = #{articleId}")
    ArticlePost selectByArticleId(@Param("articleId") String articleId);

}