DROP TABLE IF EXISTS `article_post`;
CREATE TABLE `article_post` (
  `id` BIGINT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
  `article_id` VARCHAR(32) NOT NULL COMMENT '文章ID',
  `title` VARCHAR(255) NOT NULL COMMENT '标题',
  `content` TEXT NOT NULL COMMENT '内容',
  `category` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '分类',
  `show_public` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否公开，0-否；1-是',
  `del_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除，0-否；1-是',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX article_id_idx(`article_id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `category`;
CREATE TABLE `article_category` (
	`id` INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    `category_name` VARCHAR(32) NOT NULL COMMENT '分类名称',
    `del_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;